# Generated by Django 4.1.1 on 2024-06-25 14:45

import cosomis.customers_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administrativelevels", "0019_administrativelevel_cvd_and_more"),
        ("subprojects", "0019_financier_level_project_step_subprojectfile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "abbreviation",
                    models.CharField(max_length=255, verbose_name="Abbreviation"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "db_table": "financial_bank",
                "unique_together": {("name",), ("abbreviation",)},
            },
        ),
        migrations.CreateModel(
            name="AdministrativeLevelAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                (
                    "amount",
                    cosomis.customers_fields.CustomerFloatRangeField(
                        verbose_name="Amount allocated"
                    ),
                ),
                (
                    "amount_in_dollars",
                    cosomis.customers_fields.CustomerFloatRangeField(
                        verbose_name="Amount allocated in dollars"
                    ),
                ),
                (
                    "allocation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Allocation Date"
                    ),
                ),
                (
                    "amount_after_signature_of_contracts",
                    cosomis.customers_fields.CustomerFloatRangeField(
                        blank=True,
                        null=True,
                        verbose_name="Amount allocated after signature of contract(s) (This is only necessary if it's a CVD)",
                    ),
                ),
                (
                    "amount_in_dollars_after_signature_of_contracts",
                    cosomis.customers_fields.CustomerFloatRangeField(
                        blank=True,
                        null=True,
                        verbose_name="Amount allocated in dollars after signature of contract(s) (This is only necessary if it's a CVD)",
                    ),
                ),
                (
                    "allocation_date_after_signature_of_contracts",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Allocation Date after signature of contract(s) (This is only necessary if it's a CVD)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "administrative_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrativelevels.administrativelevel",
                        verbose_name="Administrative level",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subprojects.component",
                        verbose_name="Component (Subcomponent)",
                    ),
                ),
                (
                    "cvd",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrativelevels.cvd",
                        verbose_name="CVD",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subprojects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "db_table": "financial_administrativeLevel_allocation",
            },
        ),
    ]
