# Generated by Django 4.1.1 on 2024-06-25 14:57

import cosomis.customers_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subprojects", "0019_financier_level_project_step_subprojectfile_and_more"),
        ("administrativelevels", "0019_administrativelevel_cvd_and_more"),
        ("financial", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisbursementRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                (
                    "amount_requested",
                    cosomis.customers_fields.CustomerFloatRangeField(
                        verbose_name="Amount requested"
                    ),
                ),
                (
                    "amount_requested_in_dollars",
                    cosomis.customers_fields.CustomerFloatRangeField(
                        verbose_name="Amount requested in dollars"
                    ),
                ),
                ("requested_date", models.DateField(verbose_name="Request date")),
                (
                    "motif",
                    models.DateField(
                        blank=True, max_length=255, null=True, verbose_name="Motif"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "reply_date",
                    models.DateField(blank=True, null=True, verbose_name="Reply date"),
                ),
                (
                    "comment_linked_to_reply",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Comment related to the request response",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subprojects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "db_table": "financial_disbursement_request",
            },
        ),
        migrations.CreateModel(
            name="Disbursement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                (
                    "amount_disbursed",
                    cosomis.customers_fields.CustomerFloatRangeField(
                        verbose_name="Amount disbursed"
                    ),
                ),
                (
                    "amount_disbursed_in_dollars",
                    cosomis.customers_fields.CustomerFloatRangeField(
                        verbose_name="Amount disbursed in dollars"
                    ),
                ),
                (
                    "disbursement_date",
                    models.DateField(verbose_name="Disbursement date"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "disbursement_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financial.disbursementrequest",
                        verbose_name="This disbursement is related to the following request",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subprojects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "db_table": "financial_disbursement",
            },
        ),
        migrations.CreateModel(
            name="BankTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                (
                    "amount_transferred",
                    cosomis.customers_fields.CustomerFloatRangeField(
                        verbose_name="Amount transferred"
                    ),
                ),
                (
                    "amount_transferred_in_dollars",
                    cosomis.customers_fields.CustomerFloatRangeField(
                        blank=True,
                        null=True,
                        verbose_name="Amount transferred in dollars",
                    ),
                ),
                (
                    "transfer_date",
                    models.DateField(null=True, verbose_name="Transfer date"),
                ),
                (
                    "motif",
                    models.DateField(
                        blank=True, max_length=255, null=True, verbose_name="Motif"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "administrative_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrativelevels.administrativelevel",
                        verbose_name="Administrative level",
                    ),
                ),
                (
                    "cvd",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrativelevels.cvd",
                        verbose_name="CVD",
                    ),
                ),
                (
                    "linked_to_allocation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financial.administrativelevelallocation",
                        verbose_name="Linked to allocation",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subprojects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "db_table": "financial_bank_transfer",
            },
        ),
    ]
