# Generated by Django 4.1.1 on 2024-06-25 13:54

import cosomis.customers_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrativelevels", "0019_administrativelevel_cvd_and_more"),
        ("subprojects", "0018_alter_subproject_full_title_of_approved_subproject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Financier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("wording", models.CharField(max_length=200, verbose_name="Wording")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("ranking", models.IntegerField(default=0, verbose_name="Ranking")),
                (
                    "amount_spent_at_this_step",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Amount spent at this stage"
                    ),
                ),
                (
                    "total_amount_spent",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Total amount spent"
                    ),
                ),
                (
                    "percent",
                    cosomis.customers_fields.CustomerFloatRangeField(
                        verbose_name="Percent"
                    ),
                ),
                ("begin", models.DateField(verbose_name="Begin")),
                ("end", models.DateField(blank=True, null=True, verbose_name="End")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "financier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subprojects.financier",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("wording", models.CharField(max_length=200, verbose_name="Wording")),
                (
                    "percent",
                    cosomis.customers_fields.CustomerFloatRangeField(
                        blank=True, null=True, verbose_name="Percent"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("ranking", models.IntegerField(default=0, verbose_name="Ranking")),
                (
                    "amount_spent_at_this_step",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Amount spent at this stage"
                    ),
                ),
                (
                    "total_amount_spent",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Total amount spent"
                    ),
                ),
                (
                    "has_levels",
                    models.BooleanField(default=False, verbose_name="Has levels"),
                ),
            ],
            options={
                "unique_together": {("ranking",)},
            },
        ),
        migrations.CreateModel(
            name="SubprojectFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                ("order", models.IntegerField(default=0)),
                ("principal", models.BooleanField(default=False)),
                ("date_taken", models.DateField()),
                ("file_type", models.CharField(default="image", max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubprojectStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("wording", models.CharField(max_length=200, verbose_name="Wording")),
                (
                    "percent",
                    cosomis.customers_fields.CustomerFloatRangeField(
                        blank=True, null=True, verbose_name="Percent"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("ranking", models.IntegerField(default=0, verbose_name="Ranking")),
                (
                    "amount_spent_at_this_step",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Amount spent at this stage"
                    ),
                ),
                (
                    "total_amount_spent",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Total amount spent"
                    ),
                ),
                ("begin", models.DateField(verbose_name="Begin")),
                ("end", models.DateField(blank=True, null=True, verbose_name="End")),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subprojects.step",
                        verbose_name="Step",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="subproject",
            name="ranking",
        ),
        migrations.AddField(
            model_name="subproject",
            name="breeders_farmers_group",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Breeders farmers group"
            ),
        ),
        migrations.AddField(
            model_name="subproject",
            name="distance_covered_by_streetlights",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Distance covered by streetlights (km)",
            ),
        ),
        migrations.AddField(
            model_name="subproject",
            name="ethnic_minority_group",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Ethnic minority group"
            ),
        ),
        migrations.AddField(
            model_name="subproject",
            name="exact_amount_spent",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Exact amount spent on the sub-project",
            ),
        ),
        migrations.AddField(
            model_name="subproject",
            name="extension_length",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Extension length (km)"
            ),
        ),
        migrations.AddField(
            model_name="subproject",
            name="has_fence",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Has a fence?"
            ),
        ),
        migrations.AddField(
            model_name="subproject",
            name="has_latrine_blocs",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Latrine blocks?"
            ),
        ),
        migrations.AddField(
            model_name="subproject",
            name="infrastructure_changed",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Infrastructure changed?"
            ),
        ),
        migrations.AddField(
            model_name="subproject",
            name="infrastructure_deleted",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Infrastructure deleted?"
            ),
        ),
        migrations.AddField(
            model_name="subproject",
            name="joint_subproject_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Subproject kit number"
            ),
        ),
        migrations.AddField(
            model_name="subproject",
            name="list_of_beneficiary_villages",
            field=models.ManyToManyField(
                blank=True,
                default=[],
                related_name="vilages_subprojects",
                to="administrativelevels.administrativelevel",
                verbose_name="Beneficiaries villages",
            ),
        ),
        migrations.AddField(
            model_name="subproject",
            name="number_of_classrooms",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Number of classrooms"
            ),
        ),
        migrations.AddField(
            model_name="subproject",
            name="number_of_latrine_blocks",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Number of latrine blocks"
            ),
        ),
        migrations.AddField(
            model_name="subproject",
            name="number_of_streetlights",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Number of streetlights installed"
            ),
        ),
        migrations.AddField(
            model_name="subproject",
            name="storage_capacity",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Storage capacity"
            ),
        ),
        migrations.AddField(
            model_name="subproject",
            name="subproject_type_designation",
            field=models.CharField(
                choices=[
                    ("Subproject", "Subproject"),
                    ("Infrastructure", "Infrastructure"),
                ],
                default="Subproject",
                max_length=100,
                verbose_name="Subproject type designation (Subproject or Infrastructure)",
            ),
        ),
        migrations.AddField(
            model_name="subproject",
            name="women_s_group",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Women's group"
            ),
        ),
        migrations.AddField(
            model_name="subproject",
            name="youth_group",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Youth group"
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="amount_of_the_care_and_maintenance_fund_expected_to_be_mobilized",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Upkeep and maintenance fund (EMI) to be mobilized",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="amount_of_the_contract_for_construction_supervisors",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Contract amount for construction supervisors BTP (CT)",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="amount_of_the_controllers_contract_in_SES",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Contract amount for SES controllers (CSES)",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="amount_of_the_facilitator_contract",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Contract amount for facilitator"
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="approval_date_cora",
            field=models.DateField(
                blank=True, null=True, verbose_name="Approval date cora"
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="canton",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrativelevels.administrativelevel",
                verbose_name="Canton",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="care_and_maintenance_amount_on_village_account",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Amount of maintenance fund (EMI) mobilized and deposited in village account",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="comments",
            field=models.TextField(blank=True, null=True, verbose_name="Comments"),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="component",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subprojects.component",
                verbose_name="Component (Subcomponent)",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="contract_amount_work_companies",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Contract amount for works companies (ET)",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="contract_companies_amount_for_efme",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Contract amount Entreprises de fourniture de mobiliers et equipements (EFME)",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="contract_number_of_work_companies",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Contract no. for work companies (ET)",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="convention",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Convention"
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="current_level_of_physical_realization_of_the_work",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Current level of physical realization of the work",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="current_status_of_the_site",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Current site status (Work in progress, Work stopped, Work abandoned, Technical acceptance, Provisional acceptance, etc.)",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="cvd",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrativelevels.cvd",
                verbose_name="CVD",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="date_of_provisional_acceptance_of_work_contracts",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Dates of provisional acceptance of work contracts (BTP or FORAGE)",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="date_of_signature_of_contract_for_construction_supervisors",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Date signature contrat controleurs de travaux BTP (CT)",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="date_of_technical_acceptance_of_work_contracts",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Dates for technical acceptance of work contracts (BTP or FORAGE)",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="date_signature_contract_controllers_in_SES",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Date signed SES controllers contract (CSES)",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="date_signature_contract_efme",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Date signature contrat entreprises de fourniture de mobiliers et equipements (EFME)",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="date_signature_contract_facilitator",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Date of signature of facilitator contract",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="date_signature_contract_work_companies",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Date of signature of works contract (ET)",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="depth_of_drilling",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Borehole depth (m)"
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="direct_beneficiaries_men",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Direct beneficiaries men"
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="direct_beneficiaries_women",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Direct beneficiaries women"
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="drilling_flow_rate",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Borehole flow (m3)"
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="estimated_cost",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Estimated cost"
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="existence_of_maintenance_and_upkeep_plan_developed_by_community",
            field=models.BooleanField(
                default=False,
                verbose_name="Existence of a maintenance and upkeep plan (EMI plan) drawn up by the community (if yes, put 1; if no, put 0)",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="expected_duration_of_the_work",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Estimated completion time (months)"
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="expected_end_date_of_the_contract",
            field=models.DateField(
                blank=True, null=True, verbose_name="Expected contract end date"
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="facilitator_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Facilitator name"
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="full_title_of_approved_subproject",
            field=models.TextField(
                max_length=255,
                verbose_name="Full title of approved sub-project (description)",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="indirect_beneficiaries_men",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Indirect beneficiaries men"
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="indirect_beneficiaries_women",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Indirect beneficiaries women"
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="intervention_unit",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Intervention unit"
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitude"),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="launch_date_of_the_construction_site_in_the_village",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Date of start of work in the village (date of notification of service order)",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="length_of_the_track",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Length of track (km)"
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="level_of_achievement_donation_certificate",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Level of donation certificate",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="link_to_subproject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subprojects.subproject",
                verbose_name="Linked to a sub-project",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="list_of_villages_crossed_by_the_track_or_electrification",
            field=models.ManyToManyField(
                blank=True,
                default=[],
                related_name="cantonal_subprojects",
                to="administrativelevels.administrativelevel",
                verbose_name="List of villages where the runway or electrification crosses",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="location_subproject_realized",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_subproject_realized",
                to="administrativelevels.administrativelevel",
                verbose_name="Subproject location",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitude"),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="lot",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Lot"
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="name_of_company_awarded_efme",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Name of contractor entreprises de fourniture de mobiliers et equipements (EFME)",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="name_of_the_awarded_company_works_companies",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Name of company awarded work contract (ET)",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="number",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Number unique to each sub-project or infrastructure",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="official_handover_date_of_the_microproject_to_the_community",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Date of official handover of the microproject to the community",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="official_handover_date_of_the_microproject_to_the_sector",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Date of official handover of the microproject to the sector",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="population",
            field=models.IntegerField(blank=True, null=True, verbose_name="Population"),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="priorities",
            field=models.ManyToManyField(
                blank=True,
                default=[],
                related_name="priorities_covered",
                to="subprojects.villagepriority",
                verbose_name="Priorities",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="provisional_acceptance_date_for_efme_contracts",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Provisional acceptance dates for furniture and equipment supply contracts",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="subproject_sector",
            field=models.CharField(max_length=100, verbose_name="Subproject sector"),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="target_female_beneficiaries",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Target female beneficiaries"
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="target_male_beneficiaries",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Target male beneficiaries"
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="target_youth_beneficiaries",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Target youth beneficiaries"
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="technical_acceptance_date_for_efme_contracts",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Technical acceptance dates for furniture and equipment supply contracts",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="total_contract_amount_paid",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Total amount of the pay contract (technical inspection + safeguard inspection + construction company + furniture company + facilitator)",
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="type_of_subproject",
            field=models.CharField(max_length=150, verbose_name="Type of structure"),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="wave",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Arbitrage wave"
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="works_type",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Works type"
            ),
        ),
        migrations.DeleteModel(
            name="SubprojectImage",
        ),
        migrations.AddField(
            model_name="subprojectstep",
            name="subproject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="subprojects.subproject",
                verbose_name="Subproject",
            ),
        ),
        migrations.AddField(
            model_name="subprojectfile",
            name="subproject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subprojects.subproject",
            ),
        ),
        migrations.AddField(
            model_name="subprojectfile",
            name="subproject_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subprojects.level",
            ),
        ),
        migrations.AddField(
            model_name="subprojectfile",
            name="subproject_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subprojects.subprojectstep",
            ),
        ),
        migrations.AddField(
            model_name="level",
            name="subproject_step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="subprojects.subprojectstep",
                verbose_name="Step",
            ),
        ),
        migrations.AddField(
            model_name="subproject",
            name="financiers",
            field=models.ManyToManyField(
                blank=True,
                default=[],
                to="subprojects.financier",
                verbose_name="Financiers",
            ),
        ),
        migrations.AddField(
            model_name="subproject",
            name="projects",
            field=models.ManyToManyField(
                blank=True,
                default=[],
                to="subprojects.project",
                verbose_name="Projects",
            ),
        ),
    ]
