# Generated by Django 4.1.1 on 2024-07-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subprojects", "0019_financier_level_project_step_subprojectfile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subproject",
            name="project_management",
            field=models.CharField(
                blank=True,
                choices=[("MOC", "MOC"), ("MODC", "MODC")],
                default="",
                max_length=100,
                null=True,
                verbose_name="Project management",
            ),
        ),
    ]
