# Generated by Django 4.1.1 on 2024-06-25 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrativelevels", "0018_remove_administrativelevel_cvd_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrativelevel",
            name="cvd",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrativelevels.cvd",
                verbose_name="CVD",
            ),
        ),
        migrations.AddField(
            model_name="administrativelevel",
            name="frontalier",
            field=models.BooleanField(default=True, verbose_name="Frontalier"),
        ),
        migrations.AddField(
            model_name="administrativelevel",
            name="geographical_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrativelevels.geographicalunit",
                verbose_name="Geographical unit",
            ),
        ),
        migrations.AddField(
            model_name="administrativelevel",
            name="rural",
            field=models.BooleanField(default=True, verbose_name="Rural"),
        ),
    ]
