# Generated by Django 4.1.1 on 2024-07-12 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_technical_facilitator_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    group, created = Group.objects.get_or_create(name='technical_facilitator')
    if created:
        print('Group "technical_facilitator" created successfully!')
    else:
        print('Group "technical_facilitator" already exists!')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("administrativelevels", "0019_administrativelevel_cvd_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignedTo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                (
                    "administrative_level",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrativelevels.administrativelevel",
                    ),
                ),
                (
                    "cvd",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrativelevels.cvd",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(create_technical_facilitator_group),
    ]